# Generated by Django 4.2.1 on 2023-05-23 18:49
import json
import os

from django.db import migrations


def load_currencies_names(apps, schema_editor):
    with open(os.path.join("fixtures", "currencies_names.json")) as file:
        data = json.load(file)

        CurrencyName = apps.get_model('currency', 'CurrencyName')

        currencies = map(lambda x: CurrencyName(**x), data)
        CurrencyName.objects.bulk_create(currencies)


def delete_currencies_names(apps, schema_editor):
    CurrencyName = apps.get_model('currency', 'CurrencyName')



class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = []
